"""add_per_pass_json_columns_to_knowledge_models

Revision ID: 2fa022c93fe4
Revises: 20260615_0008
Create Date: 2026-06-16 01:08:39.267116

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa022c93fe4'
down_revision = '20260615_0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_models', sa.Column('pass_1_json', sa.JSON(), nullable=True))
    op.add_column('knowledge_models', sa.Column('pass_2_json', sa.JSON(), nullable=True))
    op.add_column('knowledge_models', sa.Column('pass_3_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_models', 'pass_3_json')
    op.drop_column('knowledge_models', 'pass_2_json')
    op.drop_column('knowledge_models', 'pass_1_json')
    # ### end Alembic commands ###

